# Generated by Django 5.2 on 2026-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('casa', models.CharField(max_length=100)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto'), ('desconocido', 'Desconocido')], default='vivo', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='got_imegen/')),
            ],
        ),
    ]
